# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: taskbook.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etaskbook.proto\x12\x07tasking\"C\n\x08Metadata\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x12\n\nlineNumber\x18\x02 \x01(\t\x12\x11\n\tgitAuthor\x18\x03 \x01(\t\"H\n\x04Todo\x12\r\n\x05title\x18\x01 \x02(\t\x12\x10\n\x08priority\x18\x02 \x01(\t\x12\x1f\n\x04meta\x18\x03 \x01(\x0b\x32\x11.tasking.Metadata\"(\n\x08TodoList\x12\x1c\n\x05todos\x18\x01 \x03(\x0b\x32\r.tasking.Todo')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'taskbook_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METADATA._serialized_start=27
  _METADATA._serialized_end=94
  _TODO._serialized_start=96
  _TODO._serialized_end=168
  _TODOLIST._serialized_start=170
  _TODOLIST._serialized_end=210
# @@protoc_insertion_point(module_scope)
